### PR TITLE
adding fix for failed fix path

### PR DESCRIPTION
**Pull request by yuleib**
adding fix for failed fix path

### CODE REVIEW

**Comment by shm12** [comment]
Hi. I'm happy to see that you are embracing this project :)

**Comment by shm12** [comment]
The monaco editor has built-in features for marking code. Maybe in the future it will be better to use it

**Review by YiscahLevySilas1 — APPROVED** [review]

**Comment by yuleib** [comment]
Very good contribution @shm12 , thank you :)

**Comment by shm12** [comment]
Just making sure, have you [deployed](https://github.com/kubescape/regolibrary-playground#deployment) the new code?
Anyway, you will probably want a github action that will do that every time there is a push to the master branch

**Comment by shm12** [comment]
And maybe another github action that checks once in a while for a new regolibrary version, build the wasm bundle (since you disabled it in the regolibrary release) and push it to repo

**Pull request merged**
